version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  init-db:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./init.sql:/init.sql
    entrypoint: >
      /bin/bash -c "
      sleep 20;
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P 'YourStrong@Password123' -i /init.sql;
      echo 'Database initialized';
      "
  zoo-api:
    build:
      context: ./  # Path to your .NET project folder
      dockerfile: Dockerfile  # Specify the Dockerfile if it's not named 'Dockerfile'
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=your_db_name;User Id=sa;Password=YourStrong@Password123;
    ports:
      - "8084:8080"  # Change port if necessary
  frontend:
    image: nginx:alpine
    depends_on:
      - zoo-api
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./zoo-animal-manager-system/dist:/usr/share/nginx/html
    ports:
      - "3000:80"
volumes:
  sql_data:
