version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  init-db:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./init.sql:/init.sql
#    entrypoint:
#    entrypoint: >
#      bash -c "dotnet tool install --global dotnet-ef &&
#             export PATH=\"$PATH:/root/.dotnet/tools\" &&
#              dotnet ef migrations add InitialCreate &&
#             dotnet ef database update &&
#             dotnet ZooApi.dll"
  zoo-api:
    build:
      context: ./
      dockerfile: Dockerfile
    platform: linux/amd64
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=your_db_name;User Id=sa;Password=YourStrong@Password123;
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8084:8080"  # Change port if necessary
  frontend:
    build:
      context: ./zoo-animal-manager-system  # Path to your React app directory
      dockerfile: Dockerfile  # Specify the Dockerfile if it's not named 'Dockerfile'
    depends_on:
      - zoo-api
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Nginx configuration
    ports:
      - "3000:80"  # Expose the Nginx server on port 3000
volumes:
  sql_data:
